#!/bin/zsh

# locale
# ======
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# set window title
# ================
setWindowTitle() { print -Pn "\e]0;${1}\a" }

# exa
# ===
alias ls='exa'

# nix
# ===
if [[ -f ${HOME}/.nix-profile/etc/profile.d/nix.sh ]]; then
  source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
fi

# editor
# ======
export EDITOR='vim'

# zplug
# =====
if [[ ! -d ~/.zplug ]]; then
    echo "installing zplug..."
    git clone https://github.com/b4b4r07/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug 'chrissicool/zsh-256color'
zplug 'zdharma/history-search-multi-word'
zplug 'zsh-users/zsh-autosuggestions', defer:2
zplug 'zdharma/fast-syntax-highlighting', defer:2
zplug 'aperezdc/zsh-fzy'
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

if ! zplug check; then
    zplug install
fi

zplug load

# history
# =======
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# git
# ===
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export DISABLE_AUTO_UPDATE="true"

# powerlevel9k
# ============
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time dir command_execution_time status)
